baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'JHU AMS Datathon 2024'

disableKinds = ["section", "taxonomy", "term", "RSS", "robotsTXT"]

theme = 'hugo-scroll'

[params]
title = 'Datathon'
favicon = "images/Johns Hopkins University-06.png"

[markup.goldmark.renderer]
unsafe= true
